### ISSUE TITLE
Analyze failed geocoding attempts

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-geosearch-acceptance-tests#6]
Consider how they can be added into the test suite and what value that will bring, make new issues for follow-on tasks.

**Comment by andycochran** [comment]
I've manually tested 185 failed ZoLa search terms, noting if/why they pass/fail in the GeoSearch. 

**Common reasons for failure:**
- Needs hyphen (will be addressed in [#22](https://github.com/NYCPlanning/labs-geosearch-pad-normalize/issues/22))
- Includes hyphen tho PAD is not hyphenated (wontfix, data issue?)
- Includes a neighborhood name after the street name, e.g.: "1634 Jefferson Ave Ridgewood" (adding a comma separator after "Ave" returns a hit)
- Includes extra zero padding after hyphen, e.g.: fail="12-020" success="12-20"
- Trailing comma
- Is an address range, not a single address (wontfix)
- Outside NYC (wontfix), e.g.: Long Island, Yonkers, etc.
- Typo (wontfix), e.g.: 
  - "12 th" instead of "12th"
  - "45East" instead of "45 East"
  - "AVE.BROOKLYN" — "AVE,BROOKLYN" works
  - many wrong spellings, stray characters, etc. 

**To do:**
- [ ] Confirm if addresses tagged "**✘ Should this work?**" in the notes should return results:
     38-37 Lawrence
     240 kent avenue
     188 seely street brooklyn
     154-18 32 avenue, queens
      5800 AVENUE U, 11234
       2 herald square
       6249 ELLWELL
- [ ] Add acceptance tests for the ones that make sense to include

**Comment by allthesignals** [comment]
Follow-up questions & issues:
 - Consider allowing people to search for ranges. In the data, people search for ranges, and this might be valuable to add.
 - Investigate range-searchers data in Analytics to see if they pasted it (there's no other string partial) and / or if they deleted and searched for non-ranges
 - Investigate why adding neighborhood names will cause searches to fail - are some neighborhood names missing from `Who's on first`? Or is the addressit parser struggling with something?
     - Would the neighborhood names be drop-ins for what is usually the boro name? 
- Check 27-20 Church - entered as a hyphenated address, but PAD does not recognize it as a hyphenated address. Let's check this to see if there's a larger pattern

**Comment by allthesignals** [comment]
This can be closed - the results have been separated into other issues
